import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "p-lounge",
    name: "Mid-Century Lounge Chair & Ottoman",
    slug: "lounge-chair",
    category: "Chairs",
    subCategory: "Lounge Chair",
    tagline: "Iconic 7-ply molded walnut shell with matching ergonomic ottoman in premium top-grain leather.",
    description: "A timeless mid-century icon. Features hand-tufted top-grain leather cushions, molded walnut plywood shell, and a 360-degree swivel die-cast base.",
    fullStory: "Originally designed to create a haven of luxurious relaxation, our Lounge Chair & Ottoman pairs architectural elegance with cloud-like ergonomics. Hand-finished with organic hardwax oils and high-resilience memory foam.",
    priceFormatted: "₹34,999",
    images: [
      "/images/lounge-chair-cream.png",
      "/images/lounge-chair-front.png",
      "/images/lounge-chair-cognac.png",
      "/images/lounge-chair-cognac-room.jpg",
    ],
    materials: [
      "Molded American Walnut Plywood",
      "Top-Grain Italian Leather",
      "Die-Cast Aluminum Base",
      "High-Density Cold-Cure Foam",
    ],
    dimensions: { width: "84 cm", depth: "85 cm", height: "84 cm" },
    finishes: [
      { name: "Cream Italian Leather & Walnut", colorCode: "#F4EFE6", imageIndex: 0 },
      { name: "Cognac Brown Leather & Walnut", colorCode: "#8B4513", imageIndex: 2 },
    ],
    features: [
      "22% Limited Anniversary Deal",
      "Includes matching ergonomic ottoman",
      "360° smooth swivel mechanism",
      "Hand-tufted button cushioning",
    ],
    discountBadge: "22% off",
    rating: 5.0,
    dealCountdown: { days: 3, hours: 14, mins: 45, secs: 10 },
    leadTime: "In stock, white-glove delivery",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-folding",
    name: "Nordic Teak Folding Chair",
    slug: "nordic-folding-chair",
    category: "Chairs",
    subCategory: "Folding Chair",
    tagline: "Collapsible solid teak wood accent chair with woven natural sling canvas.",
    description: "Effortlessly portable without sacrificing architectural elegance. Folds flat in one fluid motion for seamless storage and indoor-outdoor versatility.",
    fullStory: "Precision crafted from sustainably harvested Grade-A Teak wood with water-resistant heavy-gauge canvas seating.",
    priceFormatted: "₹5,499",
    images: [
      "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=900&q=80",
      "/images/product-tufted-chair.png",
    ],
    materials: ["Solid Grade-A Teak", "Heavyweight Duck Canvas", "Stainless Steel Hinges"],
    dimensions: { width: "56 cm", depth: "60 cm", height: "82 cm" },
    finishes: [
      { name: "Natural Teak & Sand", colorCode: "#C2A676" },
      { name: "Charcoal & Teak", colorCode: "#2B2B2B" },
    ],
    features: ["15% Special Discount", "Folds completely flat", "Weather-resistant oil finish"],
    discountBadge: "15% off",
    rating: 4.8,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-dining-chair",
    name: "Scandinavian Curved Dining Chair",
    slug: "scandinavian-curved-dining-chair",
    category: "Chairs",
    subCategory: "Dining Chair",
    tagline: "Steam-bent solid ash wood dining chair with hand-woven Danish papercord seat.",
    description: "A mid-century classic with organic contours, lightweight structural joinery, and an ergonomic curved backrest that invites long dinner conversations.",
    fullStory: "Every curve is steam-bent from continuous solid European ash and hand-strung with over 120 meters of natural Danish paper cord.",
    priceFormatted: "₹6,499",
    images: [
      "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=80",
      "/images/chairs-barstool.png",
    ],
    materials: ["Solid European Ash", "Danish Paper Cord", "Natural Hardwax Oil"],
    dimensions: { width: "53 cm", depth: "54 cm", height: "76 cm" },
    finishes: [
      { name: "Natural Blonde Ash", colorCode: "#D8C5A8" },
      { name: "Smoked Black Oak", colorCode: "#222222" },
    ],
    features: ["10% Discount", "Hand-woven paper cord seat", "Ergonomic steam-bent rail"],
    discountBadge: "10% off",
    rating: 4.9,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-office-chair",
    name: "Executive Ergonomic Mesh Office Chair",
    slug: "executive-ergonomic-office-chair",
    category: "Chairs",
    subCategory: "Office Chair",
    tagline: "Breathable dual-zone mesh task chair with dynamic lumbar support and 3D armrests.",
    description: "Engineered for executive workstations and home studios. Features synchro-tilt mechanism, adjustable seat pan depth, and silent polyurethane wheels.",
    fullStory: "Designed to keep spine alignment optimal throughout 10+ hour creative and executive work sessions.",
    priceFormatted: "₹12,999",
    images: [
      "https://images.unsplash.com/photo-1580481077198-c827c413e174?auto=format&fit=crop&w=900&q=80",
      "/images/product-gaming-chair.png",
    ],
    materials: ["Breathable Korean Elastomeric Mesh", "Reinforced Aluminum Frame", "Class-4 Gas Cylinder"],
    dimensions: { width: "66 cm", depth: "68 cm", height: "128 cm" },
    finishes: [
      { name: "Slate Grey Mesh", colorCode: "#4A4A4A" },
      { name: "All Black", colorCode: "#171717" },
    ],
    features: ["18% Discount", "Multi-lock synchro tilt", "Adjustable 3D armrests"],
    discountBadge: "18% off",
    rating: 4.9,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-barstool",
    name: "Minimalist Nordic High Bar Stool",
    slug: "minimalist-nordic-bar-stool",
    category: "Chairs",
    subCategory: "Bar Stool",
    tagline: "High-perch solid oak kitchen counter bar stool with brass footrest rail.",
    description: "Elevate your kitchen island or breakfast nook. Sculpted saddle seat provides natural comfort, paired with tapered solid oak legs and brushed brass hardware.",
    fullStory: "Turned from American White Oak with integrated structural tenon joinery for heavy daily commercial and home use.",
    priceFormatted: "₹5,499",
    images: [
      "/images/chairs-barstool.png",
      "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=80",
    ],
    materials: ["Solid American White Oak", "Brushed Brass Footrest", "Felt Glide Pads"],
    dimensions: { width: "42 cm", depth: "42 cm", height: "76 cm" },
    finishes: [
      { name: "Natural Oak", colorCode: "#D4AF37" },
      { name: "Ebony Stain", colorCode: "#1C1C1C" },
    ],
    features: ["12% Discount", "Ergonomic saddle contour", "Brass foot protection rail"],
    discountBadge: "12% off",
    rating: 4.8,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-club-chair",
    name: "Chesterfield Leather Club Chair",
    slug: "chesterfield-leather-club-chair",
    category: "Chairs",
    subCategory: "Club Chair",
    tagline: "Deep-seated vintage cognac leather club chair with rolled arms and solid walnut feet.",
    description: "An enduring statement of luxury comfort. Hand-tufted with full-grain pull-up leather that develops rich patina over time, built around a heavy-duty kiln-dried hardwood frame.",
    fullStory: "Hand-aged top-grain leather upholstered with individually hand-driven antique brass nails along the graceful rolled arms.",
    priceFormatted: "₹21,999",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80",
      "/images/product-wingback.png",
    ],
    materials: ["Full-Grain Pull-Up Italian Leather", "Solid American Walnut", "High-Resilience Pocket Coils"],
    dimensions: { width: "95 cm", depth: "90 cm", height: "82 cm" },
    finishes: [
      { name: "Vintage Cognac", colorCode: "#8B4513" },
      { name: "Cigar Brown", colorCode: "#3E2723" },
    ],
    features: ["15% Special Sale", "Hand-tufted diamond buttons", "Solid walnut bun feet"],
    discountBadge: "15% off",
    rating: 5.0,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-00",
    name: "Wooden Sofa Chair",
    slug: "wooden-sofa-chair",
    category: "Chairs",
    subCategory: "Armchair",
    tagline: "Tufted high-back dining and accent armchair with solid wooden tapered legs.",
    description: "Upholstered in rich linen-weave cream fabric with deep diamond button tufting and solid hardwood frame.",
    fullStory: "Crafted for refined dining rooms and executive suites with ergonomic lumbar contouring and solid oak legs.",
    priceFormatted: "₹7,999",
    images: [
      "/images/product-tufted-chair.png",
      "/images/chairs-barstool.png",
    ],
    materials: ["Solid Oak Frame", "Linen Weave Fabric", "High-Density Foam"],
    dimensions: { width: "58 cm", depth: "62 cm", height: "98 cm" },
    finishes: [
      { name: "Cream Linen", colorCode: "#F5F2EB" },
      { name: "Charcoal Grey", colorCode: "#3C3C3C" },
    ],
    features: [
      "50% Limited Flash Sale",
      "Hand-tufted button back",
      "Solid hardwood legs",
    ],
    discountBadge: "50% off",
    rating: 4.9,
    dealCountdown: { days: 5, hours: 12, mins: 30, secs: 25 },
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-01",
    name: "Circular Sofa Chair",
    slug: "circular-sofa-chair",
    category: "Chairs",
    subCategory: "Lounge Chair",
    tagline: "Ergonomic round papasan lounge chair with plush tufted cream cushion and natural rattan base.",
    description: "Designed for ultimate relaxation. Features an encompassing curved bowl frame and ultra-soft tufted cushion.",
    fullStory: "Our circular sofa chair brings bohemian warmth and mid-century modern comfort to any living or reading corner.",
    priceFormatted: "₹8,999",
    images: [
      "/images/product-papasan.png",
      "/images/sofa-tufted.png",
    ],
    materials: ["Solid Rattan Frame", "High-Resilience Wool Cushion", "Natural Hardwax Oil"],
    dimensions: { width: "90 cm", depth: "90 cm", height: "80 cm" },
    finishes: [
      { name: "Natural Cane", colorCode: "#E2C9A5" },
      { name: "Smoked Oak", colorCode: "#5C4033" },
    ],
    features: [
      "10% Limited Discount Applied",
      "Removable & washable cushion cover",
      "Supports up to 150 kg",
    ],
    discountBadge: "10% off",
    rating: 5.0,
    leadTime: "In stock, ships in 2-3 days",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-02",
    name: "Wooden Nightstand",
    slug: "wooden-nightstand",
    category: "Bedroom",
    tagline: "Minimalist two-drawer solid oak nightstand with tapered mid-century legs.",
    description: "Compact dual-tier bedside storage with soft-close brass hardware and continuous wood grain joinery.",
    fullStory: "Precision cut from American White Oak with smooth ball-bearing drawer glides and integrated cord pass.",
    priceFormatted: "₹4,499",
    images: [
      "/images/product-nightstand.png",
      "https://images.unsplash.com/photo-1532323544230-7191fd51bc1b?auto=format&fit=crop&w=900&q=80",
    ],
    materials: ["Solid American Oak", "Brushed Brass Handles", "Felt Drawer Liners"],
    dimensions: { width: "48 cm", depth: "40 cm", height: "52 cm" },
    finishes: [
      { name: "Natural Oak", colorCode: "#D8B48D" },
      { name: "Walnut Stain", colorCode: "#51361F" },
    ],
    features: ["10% Discount", "Soft-close dual drawers", "Pre-assembled"],
    discountBadge: "10% off",
    rating: 4.8,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-03",
    name: "Bean Bag Chair",
    slug: "bean-bag-chair",
    category: "Chairs",
    subCategory: "Lounge Chair",
    tagline: "Relaxed slouch armchair in distressed cognac vegan leather with micro-bead filling.",
    description: "Casual lounging perfected. Conforms to your body shape with reinforced double-stitched seams.",
    priceFormatted: "₹5,999",
    images: [
      "/images/product-beanbag.png",
      "/images/product-papasan.png",
    ],
    materials: ["Top Grain Cognac Leather / Canvas", "Virgin EPS Micro-bead Filling"],
    dimensions: { width: "85 cm", depth: "85 cm", height: "75 cm" },
    finishes: [
      { name: "Cognac Tan", colorCode: "#964B00" },
      { name: "Charcoal Grey", colorCode: "#333333" },
    ],
    features: ["10% Discount", "Double zippered safety lock", "Water-resistant"],
    discountBadge: "10% off",
    rating: 4.8,
    leadTime: "In stock",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-04",
    name: "Wingback Armchair",
    slug: "wingback-armchair",
    category: "Chairs",
    subCategory: "Armchair",
    tagline: "Classic tufted leather wingback armchair with brass nailhead trim.",
    description: "Stately fireside armchair offering ergonomic back support and hand-rubbed antique leather patina.",
    priceFormatted: "₹14,999",
    images: [
      "/images/product-wingback.png",
      "/images/product-tufted-chair.png",
    ],
    materials: ["Kiln-Dried Solid Birch Frame", "Full Grain Italian Leather", "Brass Studs"],
    dimensions: { width: "82 cm", depth: "88 cm", height: "105 cm" },
    finishes: [
      { name: "Oxblood Leather", colorCode: "#6B1D2F" },
      { name: "Caramel Brown", colorCode: "#8B5A2B" },
    ],
    features: ["20% Special Sale", "Hand-tufted diamond quilting", "10-Year Frame Warranty"],
    leadTime: "Ships in 3-5 days",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-05",
    name: "Ergonomic Gaming Chair",
    slug: "ergonomic-gaming-chair",
    category: "Chairs",
    subCategory: "Gaming Chair",
    tagline: "High-back racing executive chair with adjustable 4D armrests and lumbar support.",
    description: "Engineered for marathon focus. Features breathable perforated leatherette, steel chassis, and 165° recline.",
    priceFormatted: "₹9,499",
    images: [
      "/images/product-gaming-chair.png",
      "/images/product-tufted-chair.png",
    ],
    materials: ["Steel Tube Frame", "Memory Foam Padding", "Breathable PU Leather"],
    dimensions: { width: "68 cm", depth: "70 cm", height: "135 cm" },
    finishes: [
      { name: "Stealth Black & Gold", colorCode: "#1F1F1F" },
      { name: "White & Carbon", colorCode: "#E0E0E0" },
    ],
    features: ["Class 4 gas lift cylinder", "360° silent caster wheels", "Multi-tilt mechanism"],
    leadTime: "In stock",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-06",
    name: "Classic Wooden Dining Chair",
    slug: "classic-wooden-dining-chair",
    category: "Dining",
    tagline: "Solid curved ash wood dining chair with natural woven cord seat.",
    description: "Mid-century Scandinavian design icon. Steam-bent back rail and hand-woven papercord seating.",
    priceFormatted: "₹6,499",
    images: [
      "/images/chairs-barstool.png",
      "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=80",
    ],
    materials: ["Solid European Ash", "Danish Paper Cord", "Non-Toxic Lacquer"],
    dimensions: { width: "53 cm", depth: "54 cm", height: "76 cm" },
    finishes: [
      { name: "Natural Ash", colorCode: "#D2B48C" },
      { name: "Matte Black", colorCode: "#111111" },
    ],
    features: ["10% Discount", "Lightweight yet structural", "Handwoven cord seat"],
    leadTime: "In stock",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-07",
    name: "Architectural Ceramic Table Lamp",
    slug: "architectural-ceramic-table-lamp",
    category: "Lighting",
    subCategory: "Table Lamps",
    tagline: "Minimalist ceramic & brass mushroom table lamp with warm ambient glow.",
    description: "A soothing lighting sculpture for nightstands and console tables with 3-step touch-dimming brass control.",
    fullStory: "Hand-thrown ceramic base paired with an acid-etched opal glass dome diffuser, providing balanced 360-degree ambient warmth without harsh glare.",
    priceFormatted: "₹3,499",
    images: [
      "/images/lighting-lamp.png",
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    ],
    materials: ["Matte Ceramic Base", "Opal Glass Diffuser", "Solid Brushed Brass"],
    dimensions: { width: "26 cm", depth: "26 cm", height: "38 cm" },
    finishes: [
      { name: "Warm Terracotta", colorCode: "#C86D51" },
      { name: "Off White Sand", colorCode: "#F5F5F0" },
    ],
    features: ["3-step capacitive touch dimmer", "Warm 2700K LED bulb included", "Fabric-braided cord"],
    discountBadge: "10% off",
    rating: 4.9,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-lamp-desk",
    name: "Nordic Minimalist Oak Desk Lamp",
    slug: "nordic-minimalist-desk-lamp",
    category: "Lighting",
    subCategory: "Table Lamps",
    tagline: "Articulated solid oak and matte black steel task lamp with precision directional light.",
    description: "Designed for focused workspaces, drafting desks, and nightstands. Smooth cantilever joints allow effortless angle adjustment.",
    fullStory: "Turned from solid European white oak and weighted with a solid cast-iron base plate to ensure rock-solid stability during repositioning.",
    priceFormatted: "₹4,299",
    images: [
      "https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?auto=format&fit=crop&w=900&q=80",
      "/images/lighting-lamp.png",
    ],
    materials: ["Solid European White Oak", "Powder-Coated Steel", "Brushed Brass Fasteners"],
    dimensions: { width: "20 cm", depth: "45 cm", height: "52 cm" },
    finishes: [
      { name: "Natural Oak & Matte Black", colorCode: "#1F1F1F" },
      { name: "Blonde Ash & White", colorCode: "#E8E8E4" },
    ],
    features: ["Flicker-free eye-care LED", "Articulated dual-axis arm", "Solid wood construction"],
    discountBadge: "15% off",
    rating: 4.8,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-lamp-floor-arc",
    name: "Sculptural Arc Brass Floor Lamp",
    slug: "sculptural-arc-brass-floor-lamp",
    category: "Lighting",
    subCategory: "Floor Lamps",
    tagline: "Graceful sweeping brass arch floor lamp with weighted Italian Carrara marble base.",
    description: "An architectural centerpiece that suspends a dome diffuser over living room sectionals or reading lounges.",
    fullStory: "Engineered with seamless telescopic brass tubing extending up to 210cm reach, anchored by a 22kg solid Italian white marble plinth.",
    priceFormatted: "₹16,499",
    images: [
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=80",
      "/images/lighting-lamp.png",
    ],
    materials: ["Spun Brushed Brass", "Solid Carrara Marble", "Dimmable Foot Switch"],
    dimensions: { width: "40 cm", depth: "180 cm", height: "215 cm" },
    finishes: [
      { name: "Brushed Brass & White Marble", colorCode: "#D4AF37" },
      { name: "Matte Black & Nero Marble", colorCode: "#1A1A1A" },
    ],
    features: ["Heavy solid marble foundation", "Rotatable dome shade", "Step-on inline dimmer switch"],
    discountBadge: "18% off",
    rating: 5.0,
    leadTime: "In stock, white-glove delivery",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-lamp-tripod",
    name: "Japanese Teak & Washi Tripod Floor Lamp",
    slug: "japanese-teak-washi-tripod-floor-lamp",
    category: "Lighting",
    subCategory: "Floor Lamps",
    tagline: "Handcrafted solid teak tripod base with textured Japanese washi paper drum shade.",
    description: "Casts an ultra-soft, warm architectural glow inspired by traditional shoji screens.",
    fullStory: "Each shade is hand-stretched using fibers from mulberry bark, creating organic grain shadows when illuminated at dusk.",
    priceFormatted: "₹11,999",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=80",
    ],
    materials: ["Solid Burmese Teak", "Handmade Washi Paper Shade", "Brass Pull Chain"],
    dimensions: { width: "50 cm", depth: "50 cm", height: "155 cm" },
    finishes: [
      { name: "Natural Warm Teak", colorCode: "#A0522D" },
      { name: "Smoked Ebony Wood", colorCode: "#262626" },
    ],
    features: ["Dual warm E27 sockets", "Solid wood joinery", "Handmade shade texture"],
    discountBadge: "12% off",
    rating: 4.9,
    leadTime: "In stock, ready to ship",
    isFeatured: false,
    inStock: true,
  },
  {
    id: "p-lamp-pendant",
    name: "Smoked Glass Pendant Chandelier",
    slug: "smoked-glass-pendant-chandelier",
    category: "Lighting",
    subCategory: "Ceiling Lamps",
    tagline: "Trio cluster ceiling pendant with mouth-blown smoked fluted glass globes and brass canopy.",
    description: "Stunning ambient lighting over dining tables, kitchen islands, and double-height stairwells.",
    fullStory: "Hand-blown in Bohemia with graduated smoked tinting, suspended by adjustable cloth-covered cords with knurled brass hardware.",
    priceFormatted: "₹14,999",
    images: [
      "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=900&q=80",
      "/images/lighting-lamp.png",
    ],
    materials: ["Hand-Blown Smoked Glass", "Solid Machined Brass", "Braided Textile Cord"],
    dimensions: { width: "65 cm", depth: "65 cm", height: "120 cm" },
    finishes: [
      { name: "Smoked Grey & Brass", colorCode: "#4B4B4B" },
      { name: "Amber Gold & Matte Bronze", colorCode: "#8C6239" },
    ],
    features: ["Adjustable cord heights", "Compatible with sloped ceilings", "Dimmable LED filaments included"],
    discountBadge: "20% off",
    rating: 4.9,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  },
  {
    id: "p-lamp-sconce",
    name: "Articulated Brass Wall Sconce",
    slug: "articulated-brass-wall-sconce",
    category: "Lighting",
    subCategory: "Wall Lamps",
    tagline: "Directional wall-mounted bedside & reading sconce with swing arm and rotatable cone shade.",
    description: "Space-saving architectural lighting with plug-in or hardwired dual installation flexibility.",
    fullStory: "Machined from solid brass billet with smooth friction pivot joints that hold exact reading angles without sagging.",
    priceFormatted: "₹4,999",
    images: [
      "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=900&q=80",
      "/images/lighting-lamp.png",
    ],
    materials: ["Solid Spun Brass", "Ceramic Socket", "Braided Gold Cord"],
    dimensions: { width: "18 cm", depth: "42 cm", height: "28 cm" },
    finishes: [
      { name: "Brushed Antique Brass", colorCode: "#C5A059" },
      { name: "Matte Black Oxide", colorCode: "#1B1B1B" },
    ],
    features: ["180° swing arm rotation", "Integrated rotary dimmer switch", "Hardwire or plug-in ready"],
    discountBadge: "10% off",
    rating: 4.8,
    leadTime: "In stock, ready to ship",
    isFeatured: false,
    inStock: true,
  },
  {
    id: "p-08",
    name: "Modern Living Sofa",
    slug: "modern-living-sofa",
    category: "Living Room",
    tagline: "Luxurious 3-seater emerald velvet modern sofa with tailored bolster cushions and tapered timber legs.",
    description: "Upholstered in rich emerald forest green velvet with plush high-resilience foam core and solid oak legs.",
    fullStory: "Our signature emerald velvet sofa combines bold Scandinavian aesthetics with deep ergonomic relaxation.",
    priceFormatted: "₹27,999",
    images: [
      "/images/product-green-sofa.png",
      "/images/sofa-tufted.png",
    ],
    materials: ["Solid Ash Frame", "Emerald Green Velvet", "High-Density Foam Core"],
    dimensions: { width: "230 cm", depth: "95 cm", height: "74 cm" },
    finishes: [
      { name: "Emerald Green Velvet", colorCode: "#18552B" },
      { name: "Oatmeal Boucle", colorCode: "#E6DEC8" },
    ],
    features: ["15% Special Discount", "Includes round bolster pillows", "Stain-resistant velvet"],
    discountBadge: "15% off",
    rating: 5.0,
    leadTime: "In stock, ready to ship",
    isFeatured: true,
    inStock: true,
  }
];

export const CATEGORIES = [
  { id: "chairs", name: "Chairs", description: "1500+ Items", image: "/images/lounge-chair-cream.png", itemCount: 1500 },
  { id: "sofa", name: "Sofa", description: "750+ Items", image: "/images/sofa-tufted.png", itemCount: 750 },
  { id: "lighting", name: "Lighting", description: "450+ Items", image: "/images/lighting-lamp.png", itemCount: 450 },
  { id: "living-room", name: "Living Room", description: "2500+ Items", image: "/images/hero-living-room.png", itemCount: 2500 },
  { id: "bedroom", name: "Bedroom", description: "1500+ Items", image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=900&q=80", itemCount: 1500 },
  { id: "dining", name: "Dining", description: "1800+ Items", image: "/images/hero-dining-room.png", itemCount: 1800 },
  { id: "office", name: "Office", description: "950+ Items", image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80", itemCount: 950 },
];

export const COMPANY_INFO = {
  name: "Furniture.",
  phone: "+91 98765 43210",
  email: "support@furniture.in",
  address: "Studio 48, 100ft Road, Indiranagar, Bengaluru, Karnataka 560038",
  hours: "Monday – Saturday: 10:00 AM – 8:00 PM IST",
  stats: [
    { label: "Years Experience", value: "14+" },
    { label: "Flagship Showrooms", value: "12+" },
    { label: "Happy Customers", value: "50k+" },
    { label: "Bespoke Designs", value: "4,500+" },
  ],
};
